import type { ScanResult, TrustReport } from "../parsers/schema.js";

// ---------------------------------------------------------------------------
// HtmlReporter
// ---------------------------------------------------------------------------

/**
 * Generate a self-contained, interactive HTML report from a ScanResult.
 *
 * Features:
 * - Inline CSS, zero external dependencies
 * - Dark / light mode toggle
 * - Sortable, filterable, searchable package table
 * - Score distribution bar chart (pure CSS)
 * - Expandable detail rows per package
 * - JSON export button
 * - Responsive layout
 */
export class HtmlReporter {
  report(result: ScanResult): string {
    const reports = result.reports ?? [];
    const tree = result.tree;
    const projectName = tree?.root ?? "unknown";
    const date = new Date().toISOString().split("T")[0];
    const direct = tree?.totalDirect ?? 0;
    const transitive = tree?.totalTransitive ?? 0;
    const overallScore = result.overallScore ?? 0;
    const summary = result.summary ?? "";

    const sorted = [...reports].sort((a, b) => (a.trustScore ?? 0) - (b.trustScore ?? 0));

    const tableRowsHtml = sorted.map((r, i) => this.buildTableRow(r, i)).join("\n");
    const chartBarsHtml = this.buildChartBars(sorted);

    // Serialize the full result for the JSON export button.
    // Convert Map to object for JSON compat.
    const jsonPayload = this.escapeHtml(
      JSON.stringify(this.toSerializable(result), null, 2),
    );

    return `<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>dep-oracle Report - ${this.escapeHtml(projectName)}</title>
<style>
${CSS_CONTENT}
</style>
</head>
<body>

<header>
  <div class="header-top">
    <h1>dep-oracle</h1>
    <div class="header-actions">
      <button id="themeToggle" aria-label="Toggle theme">Toggle Dark/Light</button>
      <button id="exportJson" aria-label="Export JSON">Export JSON</button>
    </div>
  </div>
  <p class="meta">
    Project: <strong>${this.escapeHtml(projectName)}</strong> |
    Date: <strong>${date}</strong> |
    Dependencies: <strong>${direct}</strong> direct, <strong>${transitive}</strong> transitive
  </p>
</header>

<main>
  <!-- Overall score -->
  <section class="score-card">
    <div class="score-circle ${this.scoreClass(overallScore)}">
      <span class="score-value">${overallScore}</span>
      <span class="score-label">/ 100</span>
    </div>
    <div class="score-meta">
      <h2>Overall Trust Score</h2>
      <span class="badge ${this.scoreClass(overallScore)}">${this.scoreLevel(overallScore)}</span>
      ${summary ? `<p class="summary">${this.escapeHtml(summary)}</p>` : ""}
    </div>
  </section>

  <!-- Score distribution chart -->
  <section class="chart-section">
    <h2>Score Distribution</h2>
    <div class="chart">
      ${chartBarsHtml}
    </div>
    <div class="chart-legend">
      <span class="legend safe">Safe (80-100)</span>
      <span class="legend warning">Warning (50-79)</span>
      <span class="legend critical">Critical (0-49)</span>
    </div>
  </section>

  <!-- Package table -->
  <section class="table-section">
    <h2>Package Details</h2>
    <div class="table-controls">
      <input type="text" id="searchInput" placeholder="Search packages..." aria-label="Search packages">
      <select id="filterSelect" aria-label="Filter by status">
        <option value="all">All</option>
        <option value="safe">Safe</option>
        <option value="warning">Warning</option>
        <option value="critical">Critical</option>
        <option value="zombie">Zombies</option>
      </select>
    </div>
    <div class="table-wrap">
      <table id="pkgTable">
        <thead>
          <tr>
            <th data-sort="package">Package</th>
            <th data-sort="score">Score</th>
            <th data-sort="status">Status</th>
            <th data-sort="zombie">Zombie</th>
            <th data-sort="blast">Blast Radius</th>
            <th data-sort="trend">Trend</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="pkgTableBody">
          ${tableRowsHtml}
        </tbody>
      </table>
    </div>
    <p id="noResults" class="hidden">No packages match the current filter.</p>
  </section>
</main>

<footer>
  Generated by <a href="https://github.com/ertugrulakben/dep-oracle" target="_blank" rel="noopener">dep-oracle</a>
</footer>

<!-- Hidden textarea for JSON export -->
<textarea id="jsonData" class="hidden">${jsonPayload}</textarea>

<script>
${JS_CONTENT}
</script>
</body>
</html>`;
  }

  // -------------------------------------------------------------------------
  // Table row builder
  // -------------------------------------------------------------------------

  private buildTableRow(report: TrustReport, index: number): string {
    const score = report.trustScore ?? 0;
    const cls = this.scoreClass(score);
    const level = this.scoreLevel(score);
    const zombie = report.isZombie ? "Yes" : "No";
    const blast = report.blastRadius ?? 0;
    const trend = report.trend ?? "stable";
    const trendIcon = trend === "rising" ? "&#x2191;" : trend === "declining" ? "&#x2193;" : "&#x2192;";
    const pkg = this.escapeHtml(report.package ?? "unknown");
    const version = this.escapeHtml(report.version ?? "");
    const typoRisk = report.typosquatRisk ?? 0;
    const alts = (report.alternatives ?? []).map((a) => this.escapeHtml(a));
    const metrics = report.metrics;

    const detailId = `detail-${index}`;

    let detailContent = `<div class="detail-grid">`;
    if (metrics) {
      detailContent += `<div class="metric"><span class="metric-label">Security</span><span class="metric-value">${metrics.security ?? 0}</span></div>`;
      detailContent += `<div class="metric"><span class="metric-label">Maintainer</span><span class="metric-value">${metrics.maintainer ?? 0}</span></div>`;
      detailContent += `<div class="metric"><span class="metric-label">Activity</span><span class="metric-value">${metrics.activity ?? 0}</span></div>`;
      detailContent += `<div class="metric"><span class="metric-label">Popularity</span><span class="metric-value">${metrics.popularity ?? 0}</span></div>`;
      detailContent += `<div class="metric"><span class="metric-label">Funding</span><span class="metric-value">${metrics.funding ?? 0}</span></div>`;
      detailContent += `<div class="metric"><span class="metric-label">License</span><span class="metric-value">${metrics.license ?? 0}</span></div>`;
    }
    if (typoRisk > 0.5) {
      detailContent += `<div class="metric typo-warn"><span class="metric-label">Typosquat Risk</span><span class="metric-value">${Math.round(typoRisk * 100)}%</span></div>`;
    }
    if (alts.length > 0) {
      detailContent += `<div class="metric alts"><span class="metric-label">Alternatives</span><span class="metric-value">${alts.join(", ")}</span></div>`;
    }
    detailContent += `</div>`;

    return `
          <tr class="pkg-row" data-score="${score}" data-status="${cls}" data-zombie="${report.isZombie ? "yes" : "no"}" data-package="${pkg}">
            <td><strong>${pkg}</strong><br><small>${version}</small></td>
            <td><span class="score-pill ${cls}">${score}</span></td>
            <td><span class="badge ${cls}">${level}</span></td>
            <td>${zombie}</td>
            <td>${blast} files</td>
            <td class="trend-${trend}">${trendIcon} ${trend}</td>
            <td><button class="expand-btn" data-target="${detailId}" aria-label="Toggle details">&#x25BC;</button></td>
          </tr>
          <tr class="detail-row hidden" id="${detailId}">
            <td colspan="7">${detailContent}</td>
          </tr>`;
  }

  // -------------------------------------------------------------------------
  // Chart builder
  // -------------------------------------------------------------------------

  private buildChartBars(reports: TrustReport[]): string {
    if (reports.length === 0) {
      return '<p class="empty">No data to display.</p>';
    }

    // Build buckets: 0-9, 10-19, ... 90-100
    const buckets = new Array<number>(10).fill(0);
    for (const r of reports) {
      const score = r.trustScore ?? 0;
      const bucket = Math.min(9, Math.floor(score / 10));
      buckets[bucket]++;
    }
    const maxCount = Math.max(1, ...buckets);

    return buckets
      .map((count, i) => {
        const pct = Math.round((count / maxCount) * 100);
        const label = `${i * 10}-${i === 9 ? 100 : (i + 1) * 10 - 1}`;
        const cls = i >= 8 ? "safe" : i >= 5 ? "warning" : "critical";
        return `<div class="bar-group">
        <div class="bar ${cls}" style="height:${pct}%"><span class="bar-count">${count}</span></div>
        <span class="bar-label">${label}</span>
      </div>`;
      })
      .join("\n      ");
  }

  // -------------------------------------------------------------------------
  // Helpers
  // -------------------------------------------------------------------------

  private scoreClass(score: number): string {
    if (score >= 80) return "safe";
    if (score >= 50) return "warning";
    return "critical";
  }

  private scoreLevel(score: number): string {
    if (score >= 80) return "SAFE";
    if (score >= 50) return "WARNING";
    return "CRITICAL";
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#x27;");
  }

  private toSerializable(value: unknown): unknown {
    if (value === null || value === undefined) return value;
    if (value instanceof Map) {
      const obj: Record<string, unknown> = {};
      for (const [k, v] of value.entries()) {
        obj[String(k)] = this.toSerializable(v);
      }
      return obj;
    }
    if (Array.isArray(value)) {
      return value.map((item) => this.toSerializable(item));
    }
    if (typeof value === "object") {
      const result: Record<string, unknown> = {};
      for (const [k, v] of Object.entries(value)) {
        result[k] = this.toSerializable(v);
      }
      return result;
    }
    return value;
  }
}

// ---------------------------------------------------------------------------
// Inlined CSS
// ---------------------------------------------------------------------------

const CSS_CONTENT = `
:root {
  --bg: #1a1a2e;
  --bg2: #16213e;
  --fg: #e0e0e0;
  --fg2: #a0a0a0;
  --border: #2a2a4a;
  --safe: #4caf50;
  --warning: #ff9800;
  --critical: #f44336;
  --accent: #7c4dff;
  --card-bg: #1e1e3a;
  --input-bg: #2a2a4a;
}
[data-theme="light"] {
  --bg: #fafafa;
  --bg2: #ffffff;
  --fg: #212121;
  --fg2: #757575;
  --border: #e0e0e0;
  --card-bg: #ffffff;
  --input-bg: #f5f5f5;
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
  background: var(--bg);
  color: var(--fg);
  line-height: 1.6;
  padding: 0;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

/* Header */
header {
  background: var(--bg2);
  border-bottom: 1px solid var(--border);
  padding: 1.5rem 2rem;
}
.header-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 1rem;
}
header h1 { font-size: 1.5rem; color: var(--accent); }
.header-actions { display: flex; gap: 0.5rem; }
.header-actions button {
  padding: 0.4rem 0.8rem;
  border: 1px solid var(--border);
  border-radius: 4px;
  background: var(--input-bg);
  color: var(--fg);
  cursor: pointer;
  font-size: 0.85rem;
}
.header-actions button:hover { border-color: var(--accent); }
.meta { margin-top: 0.5rem; color: var(--fg2); font-size: 0.9rem; }
.meta strong { color: var(--fg); }

/* Main */
main { max-width: 1200px; margin: 0 auto; padding: 2rem; }

/* Score card */
.score-card {
  display: flex;
  align-items: center;
  gap: 2rem;
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 2rem;
  margin-bottom: 2rem;
}
.score-circle {
  width: 120px;
  height: 120px;
  border-radius: 50%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border: 4px solid currentColor;
  flex-shrink: 0;
}
.score-circle.safe { color: var(--safe); }
.score-circle.warning { color: var(--warning); }
.score-circle.critical { color: var(--critical); }
.score-value { font-size: 2.5rem; font-weight: 700; line-height: 1; }
.score-label { font-size: 0.9rem; color: var(--fg2); }
.score-meta h2 { font-size: 1.3rem; margin-bottom: 0.5rem; }
.summary { color: var(--fg2); margin-top: 0.5rem; font-size: 0.95rem; }

/* Badges */
.badge {
  display: inline-block;
  padding: 0.15rem 0.6rem;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
.badge.safe { background: var(--safe); color: #fff; }
.badge.warning { background: var(--warning); color: #000; }
.badge.critical { background: var(--critical); color: #fff; }

/* Chart */
.chart-section {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 2rem;
}
.chart-section h2 { margin-bottom: 1rem; font-size: 1.1rem; }
.chart {
  display: flex;
  align-items: flex-end;
  gap: 4px;
  height: 160px;
  padding: 0 0.5rem;
}
.bar-group {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  height: 100%;
  justify-content: flex-end;
}
.bar {
  width: 100%;
  min-height: 2px;
  border-radius: 3px 3px 0 0;
  position: relative;
  transition: height 0.3s;
}
.bar.safe { background: var(--safe); }
.bar.warning { background: var(--warning); }
.bar.critical { background: var(--critical); }
.bar-count {
  position: absolute;
  top: -18px;
  left: 50%;
  transform: translateX(-50%);
  font-size: 0.7rem;
  color: var(--fg2);
}
.bar-label { font-size: 0.65rem; color: var(--fg2); margin-top: 4px; }
.chart-legend {
  display: flex;
  gap: 1rem;
  margin-top: 0.75rem;
  justify-content: center;
}
.legend {
  font-size: 0.8rem;
  display: flex;
  align-items: center;
  gap: 4px;
}
.legend::before {
  content: '';
  display: inline-block;
  width: 12px;
  height: 12px;
  border-radius: 2px;
}
.legend.safe::before { background: var(--safe); }
.legend.warning::before { background: var(--warning); }
.legend.critical::before { background: var(--critical); }

/* Table section */
.table-section {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 2rem;
}
.table-section h2 { margin-bottom: 1rem; font-size: 1.1rem; }
.table-controls {
  display: flex;
  gap: 0.75rem;
  margin-bottom: 1rem;
  flex-wrap: wrap;
}
.table-controls input,
.table-controls select {
  padding: 0.5rem 0.75rem;
  border: 1px solid var(--border);
  border-radius: 4px;
  background: var(--input-bg);
  color: var(--fg);
  font-size: 0.9rem;
}
.table-controls input { flex: 1; min-width: 200px; }
.table-wrap { overflow-x: auto; }
table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.9rem;
}
th, td {
  padding: 0.6rem 0.75rem;
  text-align: left;
  border-bottom: 1px solid var(--border);
}
th {
  color: var(--fg2);
  font-weight: 600;
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  cursor: pointer;
  user-select: none;
  white-space: nowrap;
}
th:hover { color: var(--fg); }
th[data-sort]::after { content: ' \\2195'; opacity: 0.3; }
.score-pill {
  display: inline-block;
  padding: 0.1rem 0.5rem;
  border-radius: 12px;
  font-weight: 600;
  font-size: 0.85rem;
}
.score-pill.safe { background: rgba(76,175,80,0.15); color: var(--safe); }
.score-pill.warning { background: rgba(255,152,0,0.15); color: var(--warning); }
.score-pill.critical { background: rgba(244,67,54,0.15); color: var(--critical); }

.trend-rising { color: var(--safe); }
.trend-declining { color: var(--critical); }
.trend-stable { color: var(--fg2); }

.expand-btn {
  background: none;
  border: 1px solid var(--border);
  border-radius: 4px;
  color: var(--fg2);
  cursor: pointer;
  padding: 0.2rem 0.4rem;
  font-size: 0.7rem;
}
.expand-btn:hover { color: var(--fg); border-color: var(--accent); }

/* Detail rows */
.detail-row td {
  padding: 1rem;
  background: var(--bg);
}
.detail-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
  gap: 0.75rem;
}
.metric {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 0.6rem 0.8rem;
  display: flex;
  flex-direction: column;
}
.metric-label { font-size: 0.75rem; color: var(--fg2); text-transform: uppercase; letter-spacing: 0.3px; }
.metric-value { font-size: 1.1rem; font-weight: 600; }
.typo-warn { border-color: var(--critical); }
.alts { grid-column: 1 / -1; }
.alts .metric-value { font-size: 0.9rem; font-weight: 400; }

/* Utility */
.hidden { display: none !important; }
.empty { color: var(--fg2); text-align: center; padding: 2rem 0; }
#noResults { text-align: center; padding: 1rem 0; color: var(--fg2); }

/* Footer */
footer {
  text-align: center;
  padding: 2rem;
  color: var(--fg2);
  font-size: 0.85rem;
  border-top: 1px solid var(--border);
}

/* Responsive */
@media (max-width: 640px) {
  header { padding: 1rem; }
  main { padding: 1rem; }
  .score-card { flex-direction: column; text-align: center; }
  .detail-grid { grid-template-columns: 1fr 1fr; }
}
`;

// ---------------------------------------------------------------------------
// Inlined JS
// ---------------------------------------------------------------------------

const JS_CONTENT = `
(function() {
  'use strict';

  // Theme toggle
  var themeBtn = document.getElementById('themeToggle');
  themeBtn.addEventListener('click', function() {
    var html = document.documentElement;
    var current = html.getAttribute('data-theme');
    html.setAttribute('data-theme', current === 'dark' ? 'light' : 'dark');
  });

  // JSON export
  var exportBtn = document.getElementById('exportJson');
  exportBtn.addEventListener('click', function() {
    var data = document.getElementById('jsonData').value;
    var blob = new Blob([data], { type: 'application/json' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'dep-oracle-report.json';
    a.click();
    URL.revokeObjectURL(url);
  });

  // Search and filter
  var searchInput = document.getElementById('searchInput');
  var filterSelect = document.getElementById('filterSelect');
  var tableBody = document.getElementById('pkgTableBody');
  var noResults = document.getElementById('noResults');

  function applyFilters() {
    var query = searchInput.value.toLowerCase();
    var filter = filterSelect.value;
    var rows = tableBody.querySelectorAll('tr.pkg-row');
    var visible = 0;

    rows.forEach(function(row) {
      var pkg = (row.getAttribute('data-package') || '').toLowerCase();
      var status = row.getAttribute('data-status') || '';
      var zombie = row.getAttribute('data-zombie') || '';
      var detailId = row.nextElementSibling ? row.nextElementSibling.id : '';

      var matchSearch = !query || pkg.indexOf(query) !== -1;
      var matchFilter = filter === 'all'
        || filter === status
        || (filter === 'zombie' && zombie === 'yes');

      if (matchSearch && matchFilter) {
        row.classList.remove('hidden');
        visible++;
      } else {
        row.classList.add('hidden');
        // Also hide detail row
        if (detailId) {
          document.getElementById(detailId).classList.add('hidden');
        }
      }
    });

    noResults.classList.toggle('hidden', visible > 0);
  }

  searchInput.addEventListener('input', applyFilters);
  filterSelect.addEventListener('change', applyFilters);

  // Expand / collapse detail rows
  document.addEventListener('click', function(e) {
    if (!e.target.classList.contains('expand-btn')) return;
    var targetId = e.target.getAttribute('data-target');
    var detail = document.getElementById(targetId);
    if (!detail) return;
    var isHidden = detail.classList.contains('hidden');
    detail.classList.toggle('hidden', !isHidden);
    e.target.textContent = isHidden ? '\\u25B2' : '\\u25BC';
  });

  // Column sorting
  var sortState = { col: null, asc: true };
  var headers = document.querySelectorAll('th[data-sort]');
  headers.forEach(function(th) {
    th.addEventListener('click', function() {
      var col = th.getAttribute('data-sort');
      if (sortState.col === col) {
        sortState.asc = !sortState.asc;
      } else {
        sortState.col = col;
        sortState.asc = true;
      }
      sortTable(col, sortState.asc);
    });
  });

  function sortTable(col, asc) {
    var rows = Array.from(tableBody.querySelectorAll('tr.pkg-row'));
    rows.sort(function(a, b) {
      var va = getSortValue(a, col);
      var vb = getSortValue(b, col);
      if (typeof va === 'number' && typeof vb === 'number') {
        return asc ? va - vb : vb - va;
      }
      va = String(va).toLowerCase();
      vb = String(vb).toLowerCase();
      return asc ? va.localeCompare(vb) : vb.localeCompare(va);
    });
    // Re-insert rows (each pkg-row followed by its detail-row)
    rows.forEach(function(row) {
      var detail = row.nextElementSibling;
      tableBody.appendChild(row);
      if (detail && detail.classList.contains('detail-row')) {
        tableBody.appendChild(detail);
      }
    });
  }

  function getSortValue(row, col) {
    switch (col) {
      case 'package': return row.getAttribute('data-package') || '';
      case 'score': return parseInt(row.getAttribute('data-score'), 10) || 0;
      case 'status': return row.getAttribute('data-status') || '';
      case 'zombie': return row.getAttribute('data-zombie') || '';
      case 'blast': return parseInt(row.cells[4].textContent, 10) || 0;
      case 'trend': return row.cells[5].textContent.trim();
      default: return '';
    }
  }
})();
`;
